#ifndef NICO_RESOURCE_INC
#define NICO_RESOURCE_INC NICO_RESOURCE_INC

#define IDI_ICON_APP 100
#define IDI_ICON_FILES 101

#define IDB_TOOLBAR 105

#define IDD_REGISTER_FILETYPES 200
#define SELECT_ALL_ID 201
#define SELECT_NONE_ID 202
#define SELECT_FREE_ID 203
#define ADD_RECBROWSE_ID 204
#define OVERWRITE_FAX_ID 205

#endif //NICO_RESOURCE_INC
